export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const USER_LOADING="USER_LOADING"
export const LOGOUT ="LOGOUT";